# Generated by Django 5.0.3 on 2024-03-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
